// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxUgs48MWQL01o1CreNxzj_wZ3hTDDdrk',
    appId: '1:756372702577:web:52af7fec0157e5081b22d0',
    messagingSenderId: '756372702577',
    projectId: 'alif-ecommerce',
    authDomain: 'alif-ecommerce.firebaseapp.com',
    storageBucket: 'alif-ecommerce.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoYHMTNZ9XV26SWx56yESAdVt5FcbJjGE',
    appId: '1:756372702577:android:1ed89eadf43e70771b22d0',
    messagingSenderId: '756372702577',
    projectId: 'alif-ecommerce',
    storageBucket: 'alif-ecommerce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOuSd1Txa7pS6ZeeH8NPieM9W3EtnGVHU',
    appId: '1:756372702577:ios:7ec5b444a2530de21b22d0',
    messagingSenderId: '756372702577',
    projectId: 'alif-ecommerce',
    storageBucket: 'alif-ecommerce.appspot.com',
    iosBundleId: 'com.example.alifECommerce',
  );
}
